volumes:
  shopping-cart-vol:

services:
  pgsql:
    image: postgres:12.11
    networks:
      - app-network
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER} 
    volumes:
      - shopping-cart-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    networks:
      - app-network
    container_name: shopping-cart-server
    build: 
      context: .
      target: dev
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    depends_on:
      pgsql:
        condition: service_healthy
    ports:
      - 5000:5000
    volumes:
      - .:/server
      - ./app:/usr/src/app

networks:
  app-network:
    external: true