volumes:
  shopping-cart-vol:

services:
  pgsql:
    image: postgres:12.11
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER} 
    volumes:
      - shopping-cart-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

  python:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - pgsql
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app